//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.09 at 08:23:15 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.soen487.com/log-ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.soen487.log_ws;
