server:
  port: 8899


spring:
  datasource:
    druid:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concordia?serverTimezone=UTC
    username: root
    password: root
  http:
    multipart:
      enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

google:
  googleBookApiUrl: "https://www.googleapis.com/books/v1/volumes?q="
